### ISSUE TITLE
newtype over string should be encoded as string ?

### ISSUE THREAD

**Issue by safareli** [eskimor/purescript-servant-support#14]
Now in `gDefaultEncodeHeader` we have a special case for string but not for newtypes over string.
so I propose change like this:

```diff
case toSpine v of
+  SProd _ [single] | SString s <- single unit -> s
  SString s -> s
  _ -> show <<< Aeson.encodeJson $ v
```

**Comment by eskimor** [comment]
Thanks for reporting! Yeah, assuming this is the behaviour on the Haskell side ;-) I don't have a PureScript installation at hand right now, could you file a PR with locally tested code? Thank you!

**Comment by dbaynard** [comment]
How do you feel @eskimor about more complicated changes, such as equivalence between haskell's `UTCTime` and purescript's `DateTime`?

I'd happily PR, too (based on code below), but I suspect there may be more issues as I build out the site.

Also, presumably there'll eventually be a move to `generics-rep` — at which point you'd want a PR with that?

---

In the frontend I'm building, I've gone with the following (using the `formatters` library). The `iso8601Format` function just uses the `formatters` combinators to match the UTCTime format (though not perfectly).

```purescript
psSettings :: SPParams_ -> SPSettings_ SPParams_
psSettings params = SPSettings_ $ defs
  { encodeJson = SPSettingsEncodeJson_ en
  , decodeJson = SPSettingsDecodeJson_ de
  }
  where
    (SPSettings_ defs) = PS.defaultSettings params

    en :: forall a . Generic a => a -> Json
    en = genericEncodeJson jsonOpts

    de :: forall a . Generic a => Json -> Either String a
    de = genericDecodeJson jsonOpts

jsonOpts :: Options
jsonOpts = let (Options opts) = Aeson.options in Options $ opts
  { userEncoding = encoding
  , userDecoding = decoding
  }

encoding :: Options -> GenericSignature -> GenericSpine -> Maybe Json
encoding o (SigProd "Data.DateTime.DateTime" _) spine = Aeson.encodeJson <<< format iso8601Format <$> fromSpine spine
encoding o sig spine = Aeson.userEncoding o sig spine

decoding :: Options -> GenericSignature -> Json -> Maybe (Either String GenericSpine)
decoding o (SigProd "Data.DateTime.DateTime" _) j = map toSpine <<< unformat iso8601Format <$> hush (Aeson.decodeJson j)
decoding o sig j = Aeson.userDecoding o sig j
```

**Comment by dbaynard** [comment]
More directly relevantly, what should happen to record style newtypes?

e.g. 
```purescript
newtype RecordNewtype = RecordNewtype
  { unRecordNewtype :: String
  }
```

(I favour the same as non-record ones)

**Comment by eskimor** [comment]
Sorry for the delay - I will properly look into your proposal, it's already on my todo list ;-)

**Comment by eskimor** [comment]
> Now in gDefaultEncodeHeader we have a special case for string but not for newtypes over string.
> so I propose change like this:
> 
> case toSpine v of
> +  SProd _ [single] | SString s <- single unit -> s
>   SString s -> s
>   _ -> show <<< Aeson.encodeJson $ v

Ok - sorry for this really long delay. No there should be no special cases for newtypes. The only reason there is a special case for String is, that there is an instance in http-api-data for it [already](https://www.stackage.org/haddock/lts-11.9/http-api-data-0.3.7.2/Web-HttpApiData.html#t:ToHttpApiData). For custom newtypes you can simply use the json representation and get frontend/backend compatibility automatically.

**Comment by eskimor** [comment]
> How do you feel @eskimor about more complicated changes, such as equivalence between haskell's UTCTime and purescript's DateTime?

This should not be achieved via purescript-servant-support, but rather by customizing [purescript-bridge defaultBridge](https://github.com/eskimor/purescript-bridge/blob/master/src/Language/PureScript/Bridge.hs#L104) to your needs (add a custom rule for UTCTime). You might also need custom encodings on the Haskell/PureScript side in order to get them compatible. If you need to customize the PureScript side, you would need to make use of the [userEncoding](https://github.com/eskimor/purescript-argonaut-generic-codecs/blob/master/src/Data/Argonaut/Generic/Options.purs#L32) and [userDecoding](https://github.com/eskimor/purescript-argonaut-generic-codecs/blob/master/src/Data/Argonaut/Generic/Options.purs#L35) options of [purescript-argonaut-generic-codecs](https://github.com/eskimor/purescript-argonaut-generic-codecs).

Hope that helps a bit. It should not be the purpose of purescript-servant-support to align types, that's what purescript-bridge and data encodings are for.

**Comment by dbaynard** [comment]
Yes, I've done both in my app, although it's probably worth waiting to see what happens with the generics-rep upgrade before PRs to those two libraries. Thanks.

**Comment by eskimor** [comment]
I am closing this issue then. Feel free to re-open, if you feel this is a mistake.
